{"name": "test_something", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'TestCase' has no attribute 'res1'", "trace": "self = <TestCases.test.TestCase object at 0x00000219AB206588>\n\n    def test_something(self):\n        print('执行测试')\n        # 获取前置方法中产生的数据\n        # 从全局变量中获取\n        # print(EnvData.data)\n        # 从当前用例的类属性中获取\n>       print(self.__class__.res1)\nE       AttributeError: type object 'TestCase' has no attribute 'res1'\n\ntest.py:32: AttributeError"}, "start": 1647351671821, "stop": 1647351671821, "uuid": "ebebf056-efef-4ebf-8f30-8ce83ad3273e", "historyId": "39a634f11d7b84a6209b18be84273ba0", "testCaseId": "5c116e581817ad4319fbae74ed49d15d", "fullName": "TestCases.test.TestCase#test_something", "labels": [{"name": "parentSuite", "value": "TestCases"}, {"name": "suite", "value": "test"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "DESKTOP-76566J4"}, {"name": "thread", "value": "12600-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "TestCases.test"}]}